variables:
  protocol: Http10
  serverUri: http://10.0.0.110:5000
  port: 5000
jobs:
  httpclient:
    source:
      localFolder: /Users/janjahoda/workspace/LibBenchmarks/
      project: HttpClientBenchmark/HttpClientBenchmark.csproj
    isConsoleApp: true
    waitForExit: true
    variables:
      warmup: 15
      duration: 15
    arguments: --server-uri {{serverUri}} --protocol {{protocol}} --warmup {{warmup}} --duration {{duration}}

  kestrel:
    source:
      localFolder: /Users/janjahoda/workspace/LibBenchmarks/
      project: ServerKestrel/ServerKestrel.csproj
    readyStateText: Server started.
    variables:
      logLevel: None
    arguments: --log-level {{logLevel}} --protocol {{protocol}} --port {{port}} --tls {% if serverUri contains "https://" %}true{% else %}false{% endif %}


scenarios:
  httpclient:
    kestrel:
      job: kestrel
    client:
      job: httpclient
